debug: false
management.endpoints.web.include: "*"

logging:
  level:
    com.example.project: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: baese
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always
  # thymeleaf.cache: false

---

spring:
  config.activate.on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board:mode=mysql
    driverClassName: org.h2.Driver
  sql.init.mode: always
  test.database.replace: none